### ISSUE TITLE
Support for Mongoose 5

### ISSUE THREAD

**Issue by dariodavi** [limit-zero/mongoose-graphql-pagination#7]
Hi, do you plan to support Mongoose 5?

getTotalCount() gives the following warning:

DeprecationWarning: collection.count is deprecated, and will be removed in a future version. Use collection.countDocuments or collection.estimatedDocumentCount instead

Thanks

**Comment by zarathustra323** [comment]
This is due to the underlying `mongodb` driver deprecating `count` in preference for `countDocuments`. I'll add a patch for this in the next few days. 

I've also been exploring an overhaul to this package (a new major version) that reduces the overall query overhead for MongoDB.

**Comment by zarathustra323** [comment]
@dariodavi This has been fixed and published to npm as `v1.1.4`
